"use client";
import { useActionState, useState } from "react";
import Link from "next/link";
import { createEventAction, publishEventAction, reorderSectionsAction, selectThemeAction, toggleSectionAction, updateEventAction } from "@/features/events/actions";
import { addGuestAction } from "@/features/guests/actions";
import { createOrderAction } from "@/features/payments/actions";
import { checkInGuestAction } from "@/features/checkin/actions";

const initial = {} as { error?: string; ok?: string };
export type SelectItem = { id: string; name: string; slug?: string; description?: string; isPremium?: boolean; price?: number };
export function NewEventForm({ types, themes }: { types: SelectItem[]; themes: SelectItem[] }) { const [state, formAction, pending] = useActionState(createEventAction, initial); return <form action={formAction} className="card mt-7 grid gap-5 p-6"><label className="label">1. Jenis acara<select name="eventTypeId" className="select" required><option value="">Pilih jenis acara</option>{types.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="label">2. Tema undangan<select name="themeId" className="select" required><option value="">Pilih tema</option>{themes.map(item => <option value={item.id} key={item.id}>{item.name}{item.isPremium ? " · Premium" : ""}</option>)}</select></label><label className="label">3. Judul acara<input name="title" className="input" required maxLength={140} placeholder="Contoh: Pernikahan Arif & Siti" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="label">Tanggal & waktu mulai<input name="startsAt" type="datetime-local" className="input" /></label><label className="label">Nama lokasi<input name="locationName" className="input" placeholder="Pendopo Arunika" /></label></div><label className="label">Alamat lokasi<textarea name="locationAddress" className="textarea" maxLength={500} /></label>{state.error && <p className="text-sm text-red-700">{state.error}</p>}<button className="button w-fit" disabled={pending}>{pending ? "Menyimpan draf…" : "Buat draf undangan"}</button></form>; }
export function EventDetailsForm({ event }: { event: { id: string; title: string; description?: string | null; startsAt?: Date | null; locationName?: string | null; locationAddress?: string | null; musicUrl?: string; musicTitle?: string } }) { const action = updateEventAction.bind(null, event.id); const [state, formAction, pending] = useActionState(action, initial); return <form action={formAction} className="card grid gap-4 p-5"><label className="label">Judul acara<input name="title" className="input" defaultValue={event.title} required /></label><label className="label">Deskripsi / salam pembuka<textarea name="description" className="textarea" defaultValue={event.description ?? ""} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="label">Mulai<input name="startsAt" type="datetime-local" className="input" defaultValue={event.startsAt?.toISOString().slice(0, 16)} /></label><label className="label">Nama lokasi<input name="locationName" className="input" defaultValue={event.locationName ?? ""} /></label></div><label className="label">Alamat<textarea name="locationAddress" className="textarea" defaultValue={event.locationAddress ?? ""} /></label><fieldset className="grid gap-4 rounded-xl border border-slate-200 p-4"><legend className="px-2 font-bold">Musik undangan</legend><p className="text-sm text-slate-600">Gunakan URL langsung ke file audio, misalnya MP3. Musik diputar setelah tamu menekan tombol play.</p><label className="label">URL lagu<input name="musicUrl" type="url" className="input" defaultValue={event.musicUrl ?? ""} placeholder="https://example.com/lagu.mp3" /></label><label className="label">Judul lagu<input name="musicTitle" className="input" maxLength={100} defaultValue={event.musicTitle ?? ""} placeholder="Lagu pilihan kami" /></label></fieldset>{state.error && <p className="text-sm text-red-700">{state.error}</p>}{state.ok && <p className="text-sm text-emerald-700">{state.ok}</p>}<button className="button w-fit" disabled={pending}>{pending ? "Menyimpan…" : "Simpan perubahan"}</button></form>; }
export function ThemeChooser({ eventId, themes, selectedId }: { eventId: string; themes: SelectItem[]; selectedId?: string | null }) { const [loading, setLoading] = useState<string>(); return <div className="grid gap-4 md:grid-cols-2">{themes.map(theme => <article className="card p-5" key={theme.id}><div className="flex justify-between gap-3"><h2 className="font-bold">{theme.name}</h2>{theme.isPremium && <span className="status">Premium</span>}</div><p className="mt-2 min-h-10 text-sm text-slate-600">{theme.description}</p><div className="mt-4 flex gap-2"><Link className="button secondary text-sm" href={`/templates/${theme.slug}`} target="_blank">Demo</Link><button className="button text-sm" disabled={loading === theme.id || selectedId === theme.id} onClick={async () => { setLoading(theme.id); await selectThemeAction(eventId, theme.id); setLoading(undefined); }}>{selectedId === theme.id ? "Sedang dipakai" : loading === theme.id ? "Memilih…" : "Gunakan tema"}</button></div></article>)}</div>; }
export function SectionsEditor({ eventId, sections }: { eventId: string; sections: { key: string; label: string; enabled: boolean; position: number }[] }) {
  const [ordered, setOrdered] = useState(() => [...sections].sort((a, b) => a.position - b.position));
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const move = async (index: number, direction: -1 | 1) => {
    const destination = index + direction;
    if (busy || destination < 0 || destination >= ordered.length || ordered[index].key === "cover") return;
    const previous = ordered;
    const next = [...ordered];
    [next[index], next[destination]] = [next[destination], next[index]];
    if (next[0].key !== "cover") return;
    setOrdered(next); setBusy(true); setMessage("");
    try { await reorderSectionsAction(eventId, next.map((section) => section.key)); }
    catch { setOrdered(previous); setMessage("Urutan belum tersimpan. Coba lagi."); }
    finally { setBusy(false); }
  };
  const toggle = async (key: string) => {
    if (busy) return;
    const previous = ordered;
    const next = ordered.map((section) => section.key === key ? { ...section, enabled: !section.enabled } : section);
    setOrdered(next); setBusy(true); setMessage("");
    try { await toggleSectionAction(eventId, key, !previous.find((section) => section.key === key)?.enabled); }
    catch { setOrdered(previous); setMessage("Perubahan belum tersimpan. Coba lagi."); }
    finally { setBusy(false); }
  };
  return <div className="grid gap-2">{ordered.map((section, index) => <div className="card flex items-center justify-between gap-3 p-4" key={section.key}><div><p className="font-semibold">{section.label}</p><p className="text-xs text-slate-500">Bagian scroll {index + 1}{section.key === "cover" ? " · selalu di awal" : ""}</p></div><div className="flex items-center gap-2"><button aria-label={`Naikkan ${section.label}`} className="button secondary px-3 text-sm" disabled={busy || index === 0 || section.key === "cover"} onClick={() => move(index, -1)}>↑</button><button aria-label={`Turunkan ${section.label}`} className="button secondary px-3 text-sm" disabled={busy || index === ordered.length - 1 || section.key === "cover"} onClick={() => move(index, 1)}>↓</button><button className="button secondary text-sm" disabled={busy || section.key === "cover"} onClick={() => toggle(section.key)}>{section.enabled ? "Aktif" : "Nonaktif"}</button></div></div>)}{message && <p role="status" className="text-sm text-red-700">{message}</p>}</div>;
}
export function GuestForm({ eventId }: { eventId: string }) { const action = addGuestAction.bind(null, eventId); const [state, formAction, pending] = useActionState(action, initial); return <form action={formAction} className="card grid gap-3 p-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-800">Tamu satuan</p><h2 className="mt-1 text-lg font-bold">Buat satu link personal</h2></div><label className="label">Nama undangan<input name="name" className="input" required placeholder="Andi dan Keluarga" /><span className="mt-1 block text-xs font-normal text-slate-500">Teks ini tampil setelah “Kepada Yth.” pada sampul.</span></label><label className="label">Grup / kategori<input name="groupName" className="input" placeholder="Keluarga, teman, rekan kerja" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="label">Telepon / WhatsApp<input name="phone" className="input" placeholder="62812…" /></label><label className="label">Jumlah kursi<input name="seats" type="number" min="1" max="20" defaultValue="1" className="input" /></label></div><label className="label">Catatan<textarea name="notes" className="textarea min-h-20" placeholder="Catatan internal, tidak tampil di undangan" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input name="isVip" type="checkbox" /> Tamu VIP</label>{state.error && <p className="text-sm text-red-700">{state.error}</p>}{state.ok && <p className="text-sm text-emerald-700">{state.ok}</p>}<button className="button w-fit" disabled={pending}>{pending ? "Membuat…" : "Buat link tamu"}</button></form>; }
export function PurchaseButton({ eventId, packageId, label }: { eventId: string; packageId: string; label: string }) { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); return <div><button className="button" disabled={busy} onClick={async () => { setBusy(true); const result = await createOrderAction(eventId, packageId); if (result.paymentUrl) window.location.href = result.paymentUrl; else setMessage("Pesanan dibuat."); setBusy(false); }}>{busy ? "Menyiapkan…" : label}</button>{message && <p className="mt-2 text-sm text-emerald-700">{message}</p>}</div>; }
export function PublishButton({ eventId, disabled }: { eventId: string; disabled: boolean }) { const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); return <div><button className="button" disabled={disabled || busy} onClick={async () => { setBusy(true); try { await publishEventAction(eventId); setMessage("Undangan sudah diterbitkan."); } catch (error) { setMessage(error instanceof Error ? error.message : "Tidak dapat menerbitkan undangan."); } finally { setBusy(false); } }}>{busy ? "Menerbitkan…" : "Terbitkan undangan"}</button>{message && <p className="mt-2 text-sm text-slate-600">{message}</p>}</div>; }
export function CheckinForm({ eventId }: { eventId: string }) { const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); return <form className="card p-5" onSubmit={async event => { event.preventDefault(); setBusy(true); const result = await checkInGuestAction(eventId, token); setMessage(result.ok ?? result.error ?? ""); setBusy(false); }}><h2 className="font-bold">Check-in manual / QR</h2><p className="mt-2 text-sm text-slate-600">Masukkan token dari QR tamu. Integrasi pemindai kamera dapat mengisi kolom yang sama.</p><label className="label mt-4">Token tamu<input className="input" value={token} onChange={event => setToken(event.target.value)} required /></label><button disabled={busy} className="button mt-4">{busy ? "Memeriksa…" : "Check-in"}</button>{message && <p role="status" className="mt-3 text-sm text-slate-700">{message}</p>}</form>; }
