export type CulturalThemeFamily = "sunda" | "jawa" | "nusantara";

export type CulturalThemeDefinition = {
  slug: string;
  name: string;
  province: string;
  family: CulturalThemeFamily;
  style: string;
  className: string;
  motion: string;
  coverLabel: string;
  greeting: string;
  ornament: string;
  colors: readonly string[];
  isPremium: boolean;
  isFeatured: boolean;
  description: string;
  tokens: Record<string, string>;
  preview: {
    src?: string;
    gradient: string;
    textClass: string;
    objectPosition?: string;
  };
  assets: Readonly<Record<string, string>>;
  visual?: {
    region: "sumatra" | "jawa" | "nusa-tenggara" | "kalimantan" | "sulawesi" | "maluku" | "papua";
    pattern: "weave" | "waves" | "petals" | "steps" | "peaks" | "islands" | "wood";
    frame: "oval" | "arch" | "diamond" | "soft-square" | "shield" | "sail" | "round";
    cadence: "breathe" | "drift" | "rise" | "ripple" | "glint" | "sway";
  };
};

const flagshipCulturalThemes = [
  {
    slug: "sunda-parahyangan",
    name: "Sunda Parahyangan",
    province: "Jawa Barat",
    family: "sunda",
    style: "sunda",
    className: "sunda",
    motion: "golek-sway",
    coverLabel: "Pawiwahan Sunda",
    greeting: "Wilujeng sumping. Terima kasih telah menjadi bagian dari hari istimewa kami.",
    ornament: "Jawa Barat · Parahyangan",
    colors: ["indigo", "gold", "sage"],
    isPremium: true,
    isFeatured: true,
    description: "Rumah Julang Ngapak, wayang golek, dan kujang dalam lanskap Parahyangan yang hangat.",
    tokens: { background: "#f6edda", primary: "#182742", accent: "#bd8a37", text: "#2d2115" },
    preview: {
      src: "/themes/sunda-parahyangan/hero.webp",
      gradient: "linear-gradient(120deg, rgba(10,24,46,.5), rgba(10,24,46,.05))",
      textClass: "text-[#fff7e6]",
      objectPosition: "center",
    },
    assets: {
      hero: "/themes/sunda-parahyangan/hero.webp",
      "hero-portrait": "/themes/sunda-parahyangan/hero-portrait.webp",
      "cover-landscape": "/themes/sunda-parahyangan/cover-landscape.webp",
      "cover-portrait": "/themes/sunda-parahyangan/cover-portrait.webp",
      wayang: "/themes/sunda-parahyangan/wayang-golek.webp",
    },
  },
  {
    slug: "jawa-wayang-heritage",
    name: "Jawa Wayang Heritage",
    province: "Jawa Tengah",
    family: "jawa",
    style: "heritage",
    className: "heritage",
    motion: "kulit-sway",
    coverLabel: "Pawiwahan Jawa",
    greeting: "Sugeng rawuh. Mugi pitedah lan panuwun becik ndherek madhangi dina istimewa punika.",
    ornament: "Jawa Tengah · Pusaka",
    colors: ["brown", "cream", "gold"],
    isPremium: true,
    isFeatured: true,
    description: "Batik parang, gunungan, dan wayang Jawa dalam panggung soga yang tenang dan berkelas.",
    tokens: { background: "#f4ead8", primary: "#3b2119", accent: "#e8c275", text: "#251a12" },
    preview: {
      src: "/themes/jawa-wayang-heritage/wayang-jawa-transparent.webp",
      gradient: "linear-gradient(120deg, rgba(45,18,14,.48), rgba(232,194,117,.12))",
      textClass: "text-[#f6d894]",
      objectPosition: "center 22%",
    },
    assets: {
      hero: "/themes/jawa-wayang-heritage/wayang-jawa-transparent.webp",
      motif: "/themes/jawa-wayang-heritage/batik-parang.webp",
      wayang: "/themes/jawa-wayang-heritage/wayang-jawa-transparent.webp",
    },
  },
  {
    slug: "serambi-meukuta",
    name: "Serambi Meukuta",
    province: "Aceh",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara aceh",
    motion: "aceh-carving",
    coverLabel: "Pernikahan Aceh",
    greeting: "Dengan takzim dan sukacita, keluarga kami menyambut kehadiran serta doa baik Anda.",
    ornament: "Aceh · Serambi Meukuta",
    colors: ["emerald", "cream", "gold"],
    isPremium: true,
    isFeatured: true,
    description: "Rumoh Aceh, ritme ukiran kayu, dan hijau zamrud yang teduh dalam komposisi lapang.",
    tokens: { background: "#f4efe3", surface: "#fffaf0", primary: "#153d32", secondary: "#d8c392", accent: "#c7a55b", text: "#20332c" },
    preview: {
      src: "/themes/serambi-meukuta/rumoh-aceh-hero.webp",
      gradient: "linear-gradient(180deg, rgba(8,30,24,.06), rgba(7,27,22,.76))",
      textClass: "text-[#fff6dd]",
      objectPosition: "58% center",
    },
    assets: {
      hero: "/themes/serambi-meukuta/rumoh-aceh-hero.webp",
      motif: "/themes/serambi-meukuta/aceh-floral-border.svg",
    },
  },
  {
    slug: "ulos-toba",
    name: "Ulos Toba",
    province: "Sumatera Utara",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara toba",
    motion: "ulos-weave",
    coverLabel: "Pernikahan Batak Toba",
    greeting: "Horas. Dengan sukacita, keluarga kami menyambut kehadiran dan doa hangat Anda.",
    ornament: "Sumatera Utara · Toba",
    colors: ["red", "charcoal", "cream"],
    isPremium: true,
    isFeatured: true,
    description: "Rumah Bolon dan Danau Toba, dibingkai merah ulos, arang, krem, dan kuningan hangat.",
    tokens: { background: "#efe7da", surface: "#fffaf1", primary: "#321f1d", secondary: "#9f352f", accent: "#d8b06a", text: "#2e2421" },
    preview: {
      src: "/themes/ulos-toba/rumah-bolon-hero.webp",
      gradient: "linear-gradient(180deg, rgba(40,22,20,.05), rgba(35,21,19,.8))",
      textClass: "text-[#fff4e1]",
      objectPosition: "48% center",
    },
    assets: {
      hero: "/themes/ulos-toba/rumah-bolon-hero.webp",
      motif: "/themes/ulos-toba/ulos-woven-border.svg",
    },
  },
  {
    slug: "rangkiang-minang",
    name: "Rangkiang Minang",
    province: "Sumatera Barat",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara minang",
    motion: "songket-glint",
    coverLabel: "Baralek Minangkabau",
    greeting: "Dengan penuh hormat, kami menyambut Bapak/Ibu/Saudara untuk berbagi kebahagiaan bersama.",
    ornament: "Sumatera Barat · Minangkabau",
    colors: ["red", "gold", "charcoal"],
    isPremium: true,
    isFeatured: true,
    description: "Rumah Gadang dan rangkiang dalam lanskap Minangkabau, dengan marun dan kilau songket.",
    tokens: { background: "#eee9df", surface: "#fffaf0", primary: "#272626", secondary: "#a84036", accent: "#d1a944", text: "#292723" },
    preview: {
      src: "/themes/rangkiang-minang/rumah-gadang-hero.webp",
      gradient: "linear-gradient(180deg, rgba(25,22,20,.05), rgba(21,18,17,.78))",
      textClass: "text-[#fff2cf]",
      objectPosition: "43% center",
    },
    assets: {
      hero: "/themes/rangkiang-minang/rumah-gadang-hero.webp",
      motif: "/themes/rangkiang-minang/songket-rhythm.svg",
    },
  },
  {
    slug: "melayu-lancang",
    name: "Melayu Lancang",
    province: "Riau",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara riau",
    motion: "melayu-sulur",
    coverLabel: "Pernikahan Melayu Riau",
    greeting: "Dengan segala hormat dan sukacita, kami menjemput Anda hadir dalam hari bahagia keluarga kami.",
    ornament: "Riau · Lancang Kuning",
    colors: ["emerald", "gold", "ivory"],
    isPremium: true,
    isFeatured: true,
    description: "Rumah panggung Melayu dan Lancang Kuning di tepian sungai, berpadu zamrud dan sulur emas.",
    tokens: { background: "#f4f0e3", surface: "#fffcf3", primary: "#16483d", secondary: "#e4d08b", accent: "#c9a343", text: "#20352e" },
    preview: {
      src: "/themes/melayu-lancang/rumah-melayu-hero.webp",
      gradient: "linear-gradient(180deg, rgba(10,49,40,.04), rgba(8,42,34,.8))",
      textClass: "text-[#fff7d6]",
      objectPosition: "64% center",
    },
    assets: {
      hero: "/themes/melayu-lancang/rumah-melayu-hero.webp",
      motif: "/themes/melayu-lancang/melayu-sulur-border.svg",
    },
  },
  {
    slug: "selat-melayu",
    name: "Selat Melayu",
    province: "Kepulauan Riau",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara kepri",
    motion: "tidal-drift",
    coverLabel: "Pernikahan Kepulauan Riau",
    greeting: "Dengan segenap hormat, kami mengundang Anda berlabuh sejenak dalam perayaan bahagia kami.",
    ornament: "Kepulauan Riau · Selat Melayu",
    colors: ["navy", "sand", "gold"],
    isPremium: true,
    isFeatured: true,
    description: "Lancang, pulau granit, dan balai pesisir dalam biru selat, pasir, serta garis peta laut.",
    tokens: { background: "#eef0ea", surface: "#fffaf0", primary: "#18384a", secondary: "#d8c7a5", accent: "#b69555", text: "#22333a" },
    preview: {
      src: "/themes/selat-melayu/selat-lancang-hero.webp",
      gradient: "linear-gradient(180deg, rgba(12,35,49,.04), rgba(8,29,43,.78))",
      textClass: "text-[#fff4d9]",
      objectPosition: "46% center",
    },
    assets: {
      hero: "/themes/selat-melayu/selat-lancang-hero.webp",
      motif: "/themes/selat-melayu/tidal-chart.svg",
    },
  },
  {
    slug: "bali-candi-bentar",
    name: "Bali Candi Bentar",
    province: "Bali",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara bali",
    motion: "candi-open",
    coverLabel: "Pawiwahan Bali",
    greeting: "Dengan rasa syukur dan sukacita, kami menyambut kehadiran Anda dalam perayaan keluarga kami.",
    ornament: "Bali · Candi Bentar",
    colors: ["terracotta", "charcoal", "moss", "gold"],
    isPremium: true,
    isFeatured: true,
    description: "Candi Bentar, atap meru, terakota, batu vulkanik, dan hijau palem dalam suasana pagi yang hening.",
    tokens: { background: "#eee5d3", surface: "#fff9ed", primary: "#302923", secondary: "#a95536", accent: "#c59a52", text: "#312721" },
    preview: {
      src: "/themes/bali-candi-bentar/candi-bentar-hero.webp",
      gradient: "linear-gradient(180deg, rgba(31,26,22,.02), rgba(35,25,19,.78))",
      textClass: "text-[#fff3dc]",
      objectPosition: "center",
    },
    assets: { hero: "/themes/bali-candi-bentar/candi-bentar-hero.webp" },
  },
  {
    slug: "sasirangan-banjar",
    name: "Sasirangan Banjar",
    province: "Kalimantan Selatan",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara banjar",
    motion: "sasirangan-ripple",
    coverLabel: "Pernikahan Banjar",
    greeting: "Dengan hangat dan penuh syukur, keluarga kami menyambut kehadiran serta doa baik Anda.",
    ornament: "Kalimantan Selatan · Banjar",
    colors: ["indigo", "violet", "teal", "gold"],
    isPremium: true,
    isFeatured: true,
    description: "Rumah Banjar Bubungan Tinggi di tepian sungai, dengan nila, ungu sasirangan, dan kuningan.",
    tokens: { background: "#eee7df", surface: "#fffaf1", primary: "#302742", secondary: "#665080", accent: "#c49a55", text: "#2b2733" },
    preview: {
      src: "/themes/sasirangan-banjar/bubungan-tinggi-hero.webp",
      gradient: "linear-gradient(180deg, rgba(37,27,52,.02), rgba(29,24,43,.8))",
      textClass: "text-[#fff1d8]",
      objectPosition: "53% center",
    },
    assets: { hero: "/themes/sasirangan-banjar/bubungan-tinggi-hero.webp" },
  },
  {
    slug: "pinisi-tongkonan",
    name: "Pinisi Tongkonan",
    province: "Sulawesi Selatan",
    family: "nusantara",
    style: "nusantara",
    className: "nusantara sulsel",
    motion: "pinisi-sail",
    coverLabel: "Pernikahan Sulawesi Selatan",
    greeting: "Dengan hormat dan sukacita, kami mengundang Anda mengiringi awal pelayaran hidup kami.",
    ornament: "Sulawesi Selatan · Pinisi",
    colors: ["navy", "teak", "ivory", "copper"],
    isPremium: true,
    isFeatured: true,
    description: "Pinisi Bulukumba dalam cahaya tembaga, dipadukan lengkung Tongkonan, kayu jati, dan biru laut.",
    tokens: { background: "#eee8dc", surface: "#fffaf0", primary: "#183144", secondary: "#8f573b", accent: "#c8874f", text: "#26313a" },
    preview: {
      src: "/themes/pinisi-tongkonan/pinisi-hero.webp",
      gradient: "linear-gradient(180deg, rgba(17,38,53,.02), rgba(15,35,49,.8))",
      textClass: "text-[#fff2d8]",
      objectPosition: "center",
    },
    assets: { hero: "/themes/pinisi-tongkonan/pinisi-hero.webp" },
  },
] as const satisfies readonly CulturalThemeDefinition[];

type RegionalThemeSeed = {
  slug: string;
  name: string;
  province: string;
  motion: string;
  coverLabel: string;
  ornament: string;
  colors: readonly string[];
  description: string;
  tokens: Record<string, string>;
  visual: NonNullable<CulturalThemeDefinition["visual"]>;
  hero?: string;
};

const regionalThemeSeeds: readonly RegionalThemeSeed[] = [
  {
    slug: "angso-duo",
    name: "Angso Duo Jambi",
    province: "Jambi",
    motion: "angso-glide",
    coverLabel: "Pernikahan Jambi",
    ornament: "Jambi · Angso Duo",
    colors: ["earth", "gold", "indigo"],
    description: "Batik Jambi, lengkung Angso Duo, dan warna tanah yang hangat dalam komposisi modern.",
    tokens: { background: "#f4eddf", surface: "#fffaf1", primary: "#342b43", secondary: "#9a673c", accent: "#c7a35b", text: "#302924" },
    visual: { region: "sumatra", pattern: "waves", frame: "oval", cadence: "drift" },
    hero: "/themes/angso-duo/hero.webp",
  },
  {
    slug: "songket-limas",
    name: "Songket Limas",
    province: "Sumatera Selatan",
    motion: "limas-rise",
    coverLabel: "Pernikahan Palembang",
    ornament: "Sumatera Selatan · Limas",
    colors: ["maroon", "black", "gold"],
    description: "Geometri Rumah Limas dan ritme songket Palembang dalam marun, hitam, dan emas tua.",
    tokens: { background: "#f2e9dc", surface: "#fff8ec", primary: "#351b22", secondary: "#7e2f37", accent: "#d0a650", text: "#2b2020" },
    visual: { region: "sumatra", pattern: "steps", frame: "arch", cadence: "rise" },
    hero: "/themes/songket-limas/hero.webp",
  },
  {
    slug: "cual-timah",
    name: "Cual Pesisir",
    province: "Kepulauan Bangka Belitung",
    motion: "cual-spark",
    coverLabel: "Pernikahan Bangka Belitung",
    ornament: "Bangka Belitung · Cual",
    colors: ["blue", "sand", "copper"],
    description: "Tenun cual, granit pesisir, dan kilau tembaga dalam palet laut yang jernih.",
    tokens: { background: "#edf0ec", surface: "#fffaf2", primary: "#21465a", secondary: "#c3a57d", accent: "#b97745", text: "#27343a" },
    visual: { region: "sumatra", pattern: "islands", frame: "diamond", cadence: "glint" },
    hero: "/themes/cual-timah/hero.webp",
  },
  {
    slug: "besurek-rafflesia",
    name: "Besurek Rafflesia",
    province: "Bengkulu",
    motion: "rafflesia-bloom",
    coverLabel: "Pernikahan Bengkulu",
    ornament: "Bengkulu · Besurek",
    colors: ["indigo", "cream", "terracotta"],
    description: "Kain besurek abstrak dan satu aksen Rafflesia yang tenang, tanpa memenuhi seluruh bidang.",
    tokens: { background: "#f1e8dd", surface: "#fff9ef", primary: "#29283f", secondary: "#9b4d3e", accent: "#c58b5d", text: "#2c2830" },
    visual: { region: "sumatra", pattern: "petals", frame: "round", cadence: "breathe" },
    hero: "/themes/besurek-rafflesia/hero.webp",
  },
  {
    slug: "siger-saibatin",
    name: "Siger Saibatin",
    province: "Lampung",
    motion: "siger-crown",
    coverLabel: "Pernikahan Lampung",
    ornament: "Lampung · Siger",
    colors: ["brick", "gold", "charcoal"],
    description: "Siluet Siger dan garis tapis dibawa ke tampilan merah bata, emas, dan arang yang berkelas.",
    tokens: { background: "#f2e8dc", surface: "#fff8ed", primary: "#322522", secondary: "#9b4236", accent: "#d0a64e", text: "#302521" },
    visual: { region: "sumatra", pattern: "peaks", frame: "shield", cadence: "rise" },
    hero: "/themes/siger-saibatin/hero.webp",
  },
  {
    slug: "betawi-gigi-balang",
    name: "Betawi Gigi Balang",
    province: "DKI Jakarta",
    motion: "gigi-balang-step",
    coverLabel: "Pernikahan Betawi",
    ornament: "Jakarta · Betawi",
    colors: ["green", "orange", "cream"],
    description: "Rumah Betawi dan ritme gigi balang dalam hijau tua, jingga bata, dan krem hangat.",
    tokens: { background: "#f4eddd", surface: "#fffaf0", primary: "#164638", secondary: "#c35d36", accent: "#d4a756", text: "#26342d" },
    visual: { region: "jawa", pattern: "steps", frame: "soft-square", cadence: "sway" },
    hero: "/themes/betawi-gigi-balang/hero.webp",
  },
  {
    slug: "jogja-kawung",
    name: "Jogja Kawung",
    province: "DI Yogyakarta",
    motion: "kawung-orbit",
    coverLabel: "Pawiwahan Yogyakarta",
    ornament: "Yogyakarta · Kawung",
    colors: ["indigo", "chalk", "antique-gold"],
    description: "Kawung, Tugu Jogja, dan ritme keraton dalam ruang lapang berwarna nila dan putih kapur.",
    tokens: { background: "#f2eee4", surface: "#fffaf1", primary: "#282d45", secondary: "#d7cfbb", accent: "#a98345", text: "#292b36" },
    visual: { region: "jawa", pattern: "petals", frame: "round", cadence: "breathe" },
    hero: "/themes/jogja-kawung/hero.webp",
  },
  {
    slug: "majapahit-terra",
    name: "Majapahit Terra",
    province: "Jawa Timur",
    motion: "majapahit-gate",
    coverLabel: "Pernikahan Jawa Timur",
    ornament: "Jawa Timur · Majapahit",
    colors: ["terracotta", "stone", "forest"],
    description: "Bata merah, relief bertingkat, dan siluet gapura Majapahit dalam suasana terakota yang teduh.",
    tokens: { background: "#eee5d8", surface: "#fff8ed", primary: "#26382f", secondary: "#a95039", accent: "#c58c53", text: "#302722" },
    visual: { region: "jawa", pattern: "steps", frame: "arch", cadence: "rise" },
    hero: "/themes/majapahit-terra/hero.webp",
  },
  {
    slug: "baduy-sederhana",
    name: "Baduy Sederhana",
    province: "Banten",
    motion: "baduy-weave",
    coverLabel: "Pernikahan Banten",
    ornament: "Banten · Baduy",
    colors: ["black", "ivory", "indigo"],
    description: "Tenun Baduy diterjemahkan secara sederhana melalui garis nila, hitam, dan ruang putih gading.",
    tokens: { background: "#f1eee5", surface: "#fffdf6", primary: "#202426", secondary: "#293e54", accent: "#b39b70", text: "#292b2b" },
    visual: { region: "jawa", pattern: "weave", frame: "soft-square", cadence: "drift" },
    hero: "/themes/baduy-sederhana/hero.webp",
  },
  {
    slug: "sasak-lumbung",
    name: "Sasak Lumbung",
    province: "Nusa Tenggara Barat",
    motion: "lumbung-breathe",
    coverLabel: "Pernikahan Sasak",
    ornament: "Nusa Tenggara Barat · Sasak",
    colors: ["straw", "red", "charcoal"],
    description: "Lengkung lumbung Sasak dan jalur songket dalam cokelat jerami, merah tenun, dan hitam.",
    tokens: { background: "#f1e8d8", surface: "#fff9ed", primary: "#342d27", secondary: "#973e36", accent: "#c79b55", text: "#302923" },
    visual: { region: "nusa-tenggara", pattern: "weave", frame: "arch", cadence: "breathe" },
    hero: "/themes/sasak-lumbung/hero.webp",
  },
  {
    slug: "tenun-flobamora",
    name: "Tenun Flobamora",
    province: "Nusa Tenggara Timur",
    motion: "flobamora-drift",
    coverLabel: "Pernikahan Flobamora",
    ornament: "Nusa Tenggara Timur · Flobamora",
    colors: ["clay", "indigo", "ivory"],
    description: "Tenun ikat dan kontur kepulauan dipadukan dalam tanah liat, nila, dan gading.",
    tokens: { background: "#f0e6d9", surface: "#fff8ec", primary: "#28364d", secondary: "#a84f3d", accent: "#c99a5a", text: "#302a29" },
    visual: { region: "nusa-tenggara", pattern: "islands", frame: "diamond", cadence: "drift" },
    hero: "/themes/tenun-flobamora/hero.webp",
  },
  {
    slug: "kapuas-rumah-panjang",
    name: "Kapuas Rumah Panjang",
    province: "Kalimantan Barat",
    motion: "kapuas-flow",
    coverLabel: "Pernikahan Kalimantan Barat",
    ornament: "Kalimantan Barat · Kapuas",
    colors: ["forest", "charcoal", "rattan"],
    description: "Aliran Kapuas, Rumah Panjang, dan aksen rotan dalam hijau hutan yang dalam.",
    tokens: { background: "#e9ece2", surface: "#fbf8ed", primary: "#173b32", secondary: "#3f5b4c", accent: "#c49b58", text: "#25332d" },
    visual: { region: "kalimantan", pattern: "waves", frame: "oval", cadence: "ripple" },
    hero: "/themes/kapuas-rumah-panjang/hero.webp",
  },
  {
    slug: "betang-borneo",
    name: "Betang Borneo",
    province: "Kalimantan Tengah",
    motion: "betang-post",
    coverLabel: "Pernikahan Kalimantan Tengah",
    ornament: "Kalimantan Tengah · Betang",
    colors: ["moss", "red-earth", "cream"],
    description: "Rumah Betang dan struktur kayu diolah menjadi garis vertikal hijau lumut dan tanah merah.",
    tokens: { background: "#ece9dc", surface: "#fff9ef", primary: "#2c4032", secondary: "#914b3a", accent: "#bd9455", text: "#2c3029" },
    visual: { region: "kalimantan", pattern: "wood", frame: "soft-square", cadence: "rise" },
    hero: "/themes/betang-borneo/hero.webp",
  },
  {
    slug: "lamin-mahakam",
    name: "Lamin Mahakam",
    province: "Kalimantan Timur",
    motion: "mahakam-current",
    coverLabel: "Pernikahan Kalimantan Timur",
    ornament: "Kalimantan Timur · Mahakam",
    colors: ["river-blue", "wood", "honey"],
    description: "Rumah Lamin dan arus Mahakam dalam biru sungai, hitam kayu, dan madu hangat.",
    tokens: { background: "#e8ece8", surface: "#fff9ee", primary: "#193d4a", secondary: "#564238", accent: "#c8994e", text: "#26343a" },
    visual: { region: "kalimantan", pattern: "waves", frame: "shield", cadence: "ripple" },
    hero: "/themes/lamin-mahakam/hero.webp",
  },
  {
    slug: "tidung-perbatasan",
    name: "Tidung Perbatasan",
    province: "Kalimantan Utara",
    motion: "tidung-leaf",
    coverLabel: "Pernikahan Kalimantan Utara",
    ornament: "Kalimantan Utara · Tidung",
    colors: ["midnight", "jungle", "sand"],
    description: "Lanskap pesisir dan jalinan serat Tidung dalam biru malam, hijau rimba, dan pasir.",
    tokens: { background: "#e9ede7", surface: "#fff9ee", primary: "#162f3d", secondary: "#275142", accent: "#c7a46b", text: "#26343a" },
    visual: { region: "kalimantan", pattern: "petals", frame: "sail", cadence: "sway" },
    hero: "/themes/tidung-perbatasan/hero.webp",
  },
  {
    slug: "minahasa-wale",
    name: "Minahasa Wale",
    province: "Sulawesi Utara",
    motion: "wale-lake",
    coverLabel: "Pernikahan Minahasa",
    ornament: "Sulawesi Utara · Wale",
    colors: ["lake-blue", "white", "gold"],
    description: "Rumah Walewangko dan kontur danau dalam biru segar, putih, dan aksen emas.",
    tokens: { background: "#eaf0ed", surface: "#fffdf6", primary: "#205068", secondary: "#8eb4b6", accent: "#c4a25e", text: "#29373d" },
    visual: { region: "sulawesi", pattern: "waves", frame: "arch", cadence: "ripple" },
    hero: "/themes/minahasa-wale/hero.webp",
  },
  {
    slug: "karawo-hulondalo",
    name: "Karawo Hulondalo",
    province: "Gorontalo",
    motion: "karawo-stitch",
    coverLabel: "Pernikahan Gorontalo",
    ornament: "Gorontalo · Karawo",
    colors: ["sky", "gold", "white"],
    description: "Sulaman Karawo yang ringan menjadi aksen sudut pada palet biru langit, emas, dan putih.",
    tokens: { background: "#edf2ee", surface: "#fffdf7", primary: "#28536b", secondary: "#9dc1c6", accent: "#c9a451", text: "#2d3940" },
    visual: { region: "sulawesi", pattern: "weave", frame: "diamond", cadence: "glint" },
    hero: "/themes/karawo-hulondalo/hero.webp",
  },
  {
    slug: "tambi-donggala",
    name: "Tambi Donggala",
    province: "Sulawesi Tengah",
    motion: "tambi-roof",
    coverLabel: "Pernikahan Sulawesi Tengah",
    ornament: "Sulawesi Tengah · Tambi",
    colors: ["coffee", "indigo", "ivory"],
    description: "Atap Rumah Tambi dan jalur tenun Donggala dalam cokelat kopi, nila, dan gading.",
    tokens: { background: "#eee7dc", surface: "#fff9ef", primary: "#302c3f", secondary: "#654536", accent: "#c49a5e", text: "#2e2928" },
    visual: { region: "sulawesi", pattern: "peaks", frame: "shield", cadence: "rise" },
    hero: "/themes/tambi-donggala/hero.webp",
  },
  {
    slug: "mandar-sandeq",
    name: "Mandar Sandeq",
    province: "Sulawesi Barat",
    motion: "sandeq-sail",
    coverLabel: "Pernikahan Mandar",
    ornament: "Sulawesi Barat · Sandeq",
    colors: ["ocean", "sail-white", "woven-red"],
    description: "Perahu Sandeq dan garis layar dalam biru laut, putih, dan merah tenun Mandar.",
    tokens: { background: "#e9efec", surface: "#fffdf5", primary: "#183f55", secondary: "#9a463d", accent: "#c49a5d", text: "#27363d" },
    visual: { region: "sulawesi", pattern: "waves", frame: "sail", cadence: "sway" },
    hero: "/themes/mandar-sandeq/hero.webp",
  },
  {
    slug: "buton-malige",
    name: "Buton Malige",
    province: "Sulawesi Tenggara",
    motion: "malige-layer",
    coverLabel: "Pernikahan Buton",
    ornament: "Sulawesi Tenggara · Malige",
    colors: ["turmeric", "indigo", "stone"],
    description: "Rumah Malige dan tenun Buton hadir lewat lapisan kunyit, nila, dan abu batu.",
    tokens: { background: "#f0eadc", surface: "#fffaf0", primary: "#29344a", secondary: "#aa7336", accent: "#c99d4d", text: "#2d302f" },
    visual: { region: "sulawesi", pattern: "steps", frame: "arch", cadence: "rise" },
    hero: "/themes/buton-malige/hero.webp",
  },
  {
    slug: "baileo-rempah",
    name: "Baileo Rempah",
    province: "Maluku",
    motion: "spice-drift",
    coverLabel: "Pernikahan Maluku",
    ornament: "Maluku · Baileo",
    colors: ["sea", "nutmeg", "cream"],
    description: "Rumah Baileo dan aksen daun pala dalam biru laut, cokelat rempah, dan krem.",
    tokens: { background: "#ebeee8", surface: "#fffaf0", primary: "#1b4755", secondary: "#7c543d", accent: "#c39a60", text: "#29363a" },
    visual: { region: "maluku", pattern: "petals", frame: "oval", cadence: "drift" },
    hero: "/themes/baileo-rempah/hero.webp",
  },
  {
    slug: "kie-hibualamo",
    name: "Kie Hibualamo",
    province: "Maluku Utara",
    motion: "kie-horizon",
    coverLabel: "Pernikahan Maluku Utara",
    ornament: "Maluku Utara · Kie",
    colors: ["sunset", "charcoal", "gold"],
    description: "Gunung Kie dan rumah Hibualamo dibingkai oranye senja, arang, dan garis horizon emas.",
    tokens: { background: "#f0e7dc", surface: "#fff9ee", primary: "#303034", secondary: "#b45b3e", accent: "#c99b50", text: "#312c2b" },
    visual: { region: "maluku", pattern: "peaks", frame: "round", cadence: "breathe" },
    hero: "/themes/kie-hibualamo/hero.webp",
  },
  {
    slug: "cenderawasih-pesisir",
    name: "Cenderawasih Pesisir",
    province: "Papua Barat",
    motion: "cenderawasih-breeze",
    coverLabel: "Pernikahan Papua Barat",
    ornament: "Papua Barat · Pesisir",
    colors: ["lagoon", "forest", "sand"],
    description: "Laguna, hutan, dan siluet pesisir yang organik tanpa menyalin motif sakral.",
    tokens: { background: "#e7eee7", surface: "#fffaf0", primary: "#174a54", secondary: "#2f604d", accent: "#c5a56d", text: "#273936" },
    visual: { region: "papua", pattern: "petals", frame: "oval", cadence: "sway" },
    hero: "/themes/cenderawasih-pesisir/hero.webp",
  },
  {
    slug: "sentani-danau",
    name: "Sentani Danau",
    province: "Papua",
    motion: "sentani-ripple",
    coverLabel: "Pernikahan Papua",
    ornament: "Papua · Sentani",
    colors: ["lake", "stone", "ochre"],
    description: "Ritme air Danau Sentani dan panorama terbuka dalam biru, abu batu, dan kuning tanah.",
    tokens: { background: "#e8eeeb", surface: "#fffaf1", primary: "#1c4b5c", secondary: "#747a73", accent: "#c49a4e", text: "#29383d" },
    visual: { region: "papua", pattern: "waves", frame: "round", cadence: "ripple" },
    hero: "/themes/sentani-danau/hero.webp",
  },
  {
    slug: "asmat-selatan",
    name: "Asmat Selatan",
    province: "Papua Selatan",
    motion: "asmat-carve",
    coverLabel: "Pernikahan Papua Selatan",
    ornament: "Papua Selatan · Asmat",
    colors: ["red-earth", "black-wood", "ivory"],
    description: "Tekstur kayu abstrak dan ritme tiang rumah Jew yang tenang, tanpa memakai objek ritual sebagai dekorasi.",
    tokens: { background: "#efe6d9", surface: "#fff9ef", primary: "#2d2926", secondary: "#94483a", accent: "#be8d5a", text: "#302a25" },
    visual: { region: "papua", pattern: "wood", frame: "shield", cadence: "rise" },
    hero: "/themes/asmat-selatan/hero.webp",
  },
  {
    slug: "kamoro-pegunungan",
    name: "Kamoro Pegunungan",
    province: "Papua Tengah",
    motion: "kamoro-contour",
    coverLabel: "Pernikahan Papua Tengah",
    ornament: "Papua Tengah · Kamoro",
    colors: ["mist", "deep-green", "copper"],
    description: "Lapisan kontur pegunungan dan pesisir dalam kabut abu-biru, hijau gelap, dan tembaga.",
    tokens: { background: "#e8ece7", surface: "#fffaf1", primary: "#26443d", secondary: "#607376", accent: "#b9784e", text: "#2b3633" },
    visual: { region: "papua", pattern: "peaks", frame: "diamond", cadence: "drift" },
  },
  {
    slug: "lembah-honai",
    name: "Lembah Honai",
    province: "Papua Pegunungan",
    motion: "honai-mist",
    coverLabel: "Pernikahan Papua Pegunungan",
    ornament: "Papua Pegunungan · Honai",
    colors: ["warm-stone", "mist", "grass"],
    description: "Siluet honai dan lereng berkabut dalam batu hangat, abu lembut, dan cokelat rumput.",
    tokens: { background: "#ece8df", surface: "#fffaf2", primary: "#3d4038", secondary: "#7d7462", accent: "#b88e58", text: "#30322e" },
    visual: { region: "papua", pattern: "peaks", frame: "round", cadence: "breathe" },
  },
  {
    slug: "raja-ampat",
    name: "Raja Ampat Arus",
    province: "Papua Barat Daya",
    motion: "raja-ampat-tide",
    coverLabel: "Pernikahan Papua Barat Daya",
    ornament: "Papua Barat Daya · Raja Ampat",
    colors: ["sapphire", "karst", "white-sand"],
    description: "Kontur karst Raja Ampat dan arus laut dalam biru safir, hijau pulau, dan pasir putih.",
    tokens: { background: "#e6eeeb", surface: "#fffdf5", primary: "#16475e", secondary: "#2e685c", accent: "#c8a86c", text: "#26383e" },
    visual: { region: "papua", pattern: "islands", frame: "sail", cadence: "ripple" },
  },
];

const regionalCulturalThemes: CulturalThemeDefinition[] = regionalThemeSeeds.map((theme) => ({
  ...theme,
  family: "nusantara",
  style: "nusantara",
  className: "nusantara regional",
  greeting: `Dengan penuh syukur, keluarga kami menyambut kehadiran dan doa baik Anda dari ${theme.province}.`,
  isPremium: true,
  isFeatured: false,
  preview: {
    src: theme.hero,
    gradient: `linear-gradient(145deg, ${theme.tokens.primary}, ${theme.tokens.secondary} 58%, ${theme.tokens.background})`,
    textClass: "text-white",
    objectPosition: "center",
  },
  assets: (theme.hero ? { hero: theme.hero } : {}) as Readonly<Record<string, string>>,
}));

export const culturalThemes: readonly CulturalThemeDefinition[] = [
  ...flagshipCulturalThemes,
  ...regionalCulturalThemes,
];

const culturalThemeBySlug = new Map<string, CulturalThemeDefinition>(
  culturalThemes.map((theme) => [theme.slug, theme]),
);

export function getCulturalTheme(slug: string) {
  return culturalThemeBySlug.get(slug);
}

export const culturalThemeStyles = Object.fromEntries(
  culturalThemes.map((theme) => [theme.slug, theme.className]),
);
